In [122]:
import numpy as np
import pandas as pd

In [123]:
dataset = pd.read_csv('C:/Users/Admin/Downloads/attirition final(1).csv')

In [124]:
dataset

Age  DailyRate    EducationField  JobSatisfaction  \
0     41       1102     Life Sciences                4   
1     49        279     Life Sciences                2   
2     37       1373             Other                3   
3     33       1392     Life Sciences                3   
4     27        591           Medical                2   
5     32       1005     Life Sciences                4   
6     59       1324           Medical                1   
7     30       1358     Life Sciences                3   
8     38        216     Life Sciences                3   
9     36       1299           Medical                3   
10    35        809           Medical                2   
11    29        153     Life Sciences                3   
12    31        670     Life Sciences                3   
13    34       1346           Medical                4   
14    28        103     Life Sciences                3   
15    29       1389     Life Sciences                1   
16    32        334     Life Sciences                2   
17    22       1123           Medical                4   
18    53       1219     Life Sciences                4   
19    38        371     Life Sciences                4   
20    24        673             Other                3   
21    36       1218     Life Sciences                1   
22    34        419     Life Sciences                2   
23    21        391     Life Sciences                4   
24    34        699           Medical                1   
25    53       1282             Other                3   
26    32       1125     Life Sciences                1   
27    42        691         Marketing                2   
28    44        477           Medical                4   
29    46        705         Marketing                1   
..   ...        ...               ...              ...   
769   26        921           Medical                3   
770   46        430           Medical                4   
771   54       1082     Life Sciences                3   
772   56       1240           Medical                3   
773   36        796           Medical                4   
774   55        444           Medical                1   
775   43        415           Medical                4   
776   20        769         Marketing                4   
777   21       1334     Life Sciences                1   
778   46       1003     Life Sciences                1   
779   51       1323     Life Sciences                3   
780   28       1366  Technical Degree                1   
781   26        192           Medical                1   
782   30       1176             Other                1   
783   41        509  Technical Degree                3   
784   38        330     Life Sciences                3   
785   40       1492  Technical Degree                4   
786   27       1277     Life Sciences                3   
787   55       1091     Life Sciences                2   
788   28        857             Other                3   
789   44       1376           Medical                1   
790   33        654     Life Sciences                4   
791   35       1204  Technical Degree                1   
792   33        827           Medical                3   
793   28        895     Life Sciences                3   
794   34        618     Life Sciences                4   
795   37        309     Life Sciences                4   
796   25       1219  Technical Degree                4   
797   26       1330           Medical                3   
798   33       1017           Medical                2   

                       JobRole  MonthlyIncome  Gender  PerformanceRating  \
0              Sales Executive           5993  Female                  3   
1           Research Scientist           5130    Male                  4   
2        Laboratory Technician           2090    Male                  3   
3           Research Scientist           2909  Female                  3   
4        Laboratory Technici

In [125]:
dataset.head()

Age  DailyRate EducationField  JobSatisfaction                JobRole  \
0   41       1102  Life Sciences                4        Sales Executive   
1   49        279  Life Sciences                2     Research Scientist   
2   37       1373          Other                3  Laboratory Technician   
3   33       1392  Life Sciences                3     Research Scientist   
4   27        591        Medical                2  Laboratory Technician   

   MonthlyIncome  Gender  PerformanceRating  TotalWorkingYears  \
0           5993  Female                  3                  8   
1           5130    Male                  4                 10   
2           2090    Male                  3                  7   
3           2909  Female                  3                  8   
4           3468    Male                  3                  6   

   WorkLifeBalance  YearsAtCompany  Attrition  
0                1               6          1  
1                3              10          0  
2                3               0          1  
3                3               8          0  
4                3               2          0

In [126]:
dataset.isnull().any()

Age                  False
DailyRate            False
EducationField       False
JobSatisfaction      False
JobRole              False
MonthlyIncome        False
Gender               False
PerformanceRating    False
TotalWorkingYears    False
WorkLifeBalance      False
YearsAtCompany       False
Attrition            False
dtype: bool

In [127]:
x=dataset.iloc[:,:11]

In [128]:
x

Age  DailyRate    EducationField  JobSatisfaction  \
0     41       1102     Life Sciences                4   
1     49        279     Life Sciences                2   
2     37       1373             Other                3   
3     33       1392     Life Sciences                3   
4     27        591           Medical                2   
5     32       1005     Life Sciences                4   
6     59       1324           Medical                1   
7     30       1358     Life Sciences                3   
8     38        216     Life Sciences                3   
9     36       1299           Medical                3   
10    35        809           Medical                2   
11    29        153     Life Sciences                3   
12    31        670     Life Sciences                3   
13    34       1346           Medical                4   
14    28        103     Life Sciences                3   
15    29       1389     Life Sciences                1   
16    32        334     Life Sciences                2   
17    22       1123           Medical                4   
18    53       1219     Life Sciences                4   
19    38        371     Life Sciences                4   
20    24        673             Other                3   
21    36       1218     Life Sciences                1   
22    34        419     Life Sciences                2   
23    21        391     Life Sciences                4   
24    34        699           Medical                1   
25    53       1282             Other                3   
26    32       1125     Life Sciences                1   
27    42        691         Marketing                2   
28    44        477           Medical                4   
29    46        705         Marketing                1   
..   ...        ...               ...              ...   
769   26        921           Medical                3   
770   46        430           Medical                4   
771   54       1082     Life Sciences                3   
772   56       1240           Medical                3   
773   36        796           Medical                4   
774   55        444           Medical                1   
775   43        415           Medical                4   
776   20        769         Marketing                4   
777   21       1334     Life Sciences                1   
778   46       1003     Life Sciences                1   
779   51       1323     Life Sciences                3   
780   28       1366  Technical Degree                1   
781   26        192           Medical                1   
782   30       1176             Other                1   
783   41        509  Technical Degree                3   
784   38        330     Life Sciences                3   
785   40       1492  Technical Degree                4   
786   27       1277     Life Sciences                3   
787   55       1091     Life Sciences                2   
788   28        857             Other                3   
789   44       1376           Medical                1   
790   33        654     Life Sciences                4   
791   35       1204  Technical Degree                1   
792   33        827           Medical                3   
793   28        895     Life Sciences                3   
794   34        618     Life Sciences                4   
795   37        309     Life Sciences                4   
796   25       1219  Technical Degree                4   
797   26       1330           Medical                3   
798   33       1017           Medical                2   

                       JobRole  MonthlyIncome  Gender  PerformanceRating  \
0              Sales Executive           5993  Female                  3   
1           Research Scientist           5130    Male                  4   
2        Laboratory Technician           2090    Male                  3   
3           Research Scientist           2909  Female                  3   
4        Laboratory Technici

In [129]:
type(x)

pandas.core.frame.DataFrame

In [130]:
x=dataset.iloc[:,:11].values

In [131]:
x

array([[41, 1102, 'Life Sciences', ..., 8, 1, 6],
       [49, 279, 'Life Sciences', ..., 10, 3, 10],
       [37, 1373, 'Other', ..., 7, 3, 0],
       ...,
       [25, 1219, 'Technical Degree', ..., 7, 4, 7],
       [26, 1330, 'Medical', ..., 1, 2, 1],
       [33, 1017, 'Medical', ..., 5, 3, 2]], dtype=object)

In [132]:
x.ndim

2

In [133]:
type(x)

numpy.ndarray

In [134]:
y=dataset.iloc[:,-1:].values

In [135]:
y.shape

(799, 1)

In [136]:
y=dataset.iloc[:,-1:].values

In [137]:
y

array([[1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [138]:
from sklearn.preprocessing import LabelEncoder
lb1=LabelEncoder()

In [139]:
x[:,2]=lb1.fit_transform(x[:,2])

In [140]:
x

array([[41, 1102, 1, ..., 8, 1, 6],
       [49, 279, 1, ..., 10, 3, 10],
       [37, 1373, 4, ..., 7, 3, 0],
       ...,
       [25, 1219, 5, ..., 7, 4, 7],
       [26, 1330, 3, ..., 1, 2, 1],
       [33, 1017, 3, ..., 5, 3, 2]], dtype=object)

In [141]:
x[:,4]=lb1.fit_transform(x[:,4])

In [142]:
x

array([[41, 1102, 1, ..., 8, 1, 6],
       [49, 279, 1, ..., 10, 3, 10],
       [37, 1373, 4, ..., 7, 3, 0],
       ...,
       [25, 1219, 5, ..., 7, 4, 7],
       [26, 1330, 3, ..., 1, 2, 1],
       [33, 1017, 3, ..., 5, 3, 2]], dtype=object)

In [143]:
x[:,6]=lb1.fit_transform(x[:,6])

In [144]:
x

array([[41, 1102, 1, ..., 8, 1, 6],
       [49, 279, 1, ..., 10, 3, 10],
       [37, 1373, 4, ..., 7, 3, 0],
       ...,
       [25, 1219, 5, ..., 7, 4, 7],
       [26, 1330, 3, ..., 1, 2, 1],
       [33, 1017, 3, ..., 5, 3, 2]], dtype=object)

In [145]:
from sklearn.preprocessing import OneHotEncoder
one= OneHotEncoder(categorical_features=[2])
x=one.fit_transform(x).toarray()

C:\anaco\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\anaco\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [146]:
x

array([[ 0.,  1.,  0., ...,  8.,  1.,  6.],
       [ 0.,  1.,  0., ..., 10.,  3., 10.],
       [ 0.,  0.,  0., ...,  7.,  3.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  7.,  4.,  7.],
       [ 0.,  0.,  0., ...,  1.,  2.,  1.],
       [ 0.,  0.,  0., ...,  5.,  3.,  2.]])

In [147]:
x=x[:,1:]

In [148]:
x

array([[ 1.,  0.,  0., ...,  8.,  1.,  6.],
       [ 1.,  0.,  0., ..., 10.,  3., 10.],
       [ 0.,  0.,  0., ...,  7.,  3.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  7.,  4.,  7.],
       [ 0.,  0.,  1., ...,  1.,  2.,  1.],
       [ 0.,  0.,  1., ...,  5.,  3.,  2.]])

In [149]:
from sklearn.preprocessing import OneHotEncoder
one= OneHotEncoder(categorical_features=[8])
x=one.fit_transform(x).toarray()

C:\anaco\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\anaco\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [150]:
x

array([[ 0.,  0.,  0., ...,  8.,  1.,  6.],
       [ 0.,  0.,  0., ..., 10.,  3., 10.],
       [ 0.,  0.,  1., ...,  7.,  3.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  7.,  4.,  7.],
       [ 0.,  0.,  1., ...,  1.,  2.,  1.],
       [ 0.,  0.,  0., ...,  5.,  3.,  2.]])

In [151]:
x=x[:,1:]

In [152]:
x

array([[ 0.,  0.,  0., ...,  8.,  1.,  6.],
       [ 0.,  0.,  0., ..., 10.,  3., 10.],
       [ 0.,  1.,  0., ...,  7.,  3.,  0.],
       ...,
       [ 0.,  1.,  0., ...,  7.,  4.,  7.],
       [ 0.,  1.,  0., ...,  1.,  2.,  1.],
       [ 0.,  0.,  0., ...,  5.,  3.,  2.]])

In [153]:
x.shape

(799, 22)

In [154]:
from sklearn.model_selection import train_test_split                #previously cros_validation was used in sklearn
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [155]:
x_test

array([[ 0.,  1.,  0., ...,  4.,  3.,  4.],
       [ 0.,  0.,  0., ..., 20.,  3., 18.],
       [ 0.,  0.,  0., ...,  4.,  2.,  4.],
       ...,
       [ 0.,  0.,  0., ..., 10.,  4.,  1.],
       [ 0.,  0.,  0., ...,  7.,  3.,  1.],
       [ 0.,  0.,  0., ..., 17.,  2.,  1.]])

In [156]:
x_test.shape

(160, 22)

In [157]:
x_train.shape

(639, 22)

In [158]:
from sklearn.preprocessing import StandardScaler#calculates mean and standard deviation,it gets alldata into same range.(mean)
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [159]:
import keras #Building neural network model back end it has tensorflow
from keras.models import Sequential # initializing model
from keras.layers import Dense # used for adding the neural network layers

In [160]:
model=Sequential()#instance

In [161]:
model.add(Dense(input_dim=22,init="random_uniform",activation="relu",output_dim=18)) #input_dim=no of neurons to have in the input layer(no of independent variables),init=adding weights,activation function,output_dim=next hidden layer
#best thing for output_dim is input_dim/2

C:\anaco\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=22, activation="relu", units=18, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [162]:
model.add(Dense(output_dim=14,init="random_uniform",activation="relu"))# adding hidden layer similary like adding weights

C:\anaco\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=14, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [163]:
model.add(Dense(input_dim=1,init="random_uniform",activation='sigmoid',output_dim=1))

C:\anaco\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=1, activation="sigmoid", units=1, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [164]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])#adam=batch gradent descent

In [165]:
model.fit(x_train,y_train,epochs=1000,batch_size=32)#epochs no of iteration 

Epoch 1/1000
639/639 [==============================] - 2s 3ms/step - loss: 0.6878 - acc: 0.8294
Epoch 2/1000
639/639 [==============================] - 0s 94us/step - loss: 0.6679 - acc: 0.8294
Epoch 3/1000
639/639 [==============================] - 0s 106us/step - loss: 0.6205 - acc: 0.8294
Epoch 4/1000
639/639 [==============================] - 0s 150us/step - loss: 0.5381 - acc: 0.8294
Epoch 5/1000
639/639 [==============================] - 0s 100us/step - loss: 0.4569 - acc: 0.8294
Epoch 6/1000
639/639 [==============================] - 0s 106us/step - loss: 0.4209 - acc: 0.8294
Epoch 7/1000
639/639 [==============================] - 0s 94us/step - loss: 0.4087 - acc: 0.8294
Epoch 8/1000
639/639 [==============================] - 0s 94us/step - loss: 0.4047 - acc: 0.8294
Epoch 9/1000
639/639 [==============================] - 0s 113us/step - loss: 0.4004 - acc: 0.8294
Epoch 10/1000
639/639 [==============================] - 0s 119us/step - loss: 0.3975 - acc: 0.8294
Epoch 11/1000


639/639 [==============================] - 0s 88us/step - loss: 0.3236 - acc: 0.8529
Epoch 84/1000
639/639 [==============================] - 0s 94us/step - loss: 0.3225 - acc: 0.8529
Epoch 85/1000
639/639 [==============================] - 0s 81us/step - loss: 0.3216 - acc: 0.8545
Epoch 86/1000
639/639 [==============================] - 0s 88us/step - loss: 0.3208 - acc: 0.8498
Epoch 87/1000
639/639 [==============================] - 0s 106us/step - loss: 0.3191 - acc: 0.8498
Epoch 88/1000
639/639 [==============================] - 0s 94us/step - loss: 0.3177 - acc: 0.8545
Epoch 89/1000
639/639 [==============================] - 0s 94us/step - loss: 0.3158 - acc: 0.8592
Epoch 90/1000
639/639 [==============================] - 0s 100us/step - loss: 0.3150 - acc: 0.8592
Epoch 91/1000
639/639 [==============================] - 0s 88us/step - loss: 0.3140 - acc: 0.8576
Epoch 92/1000
639/639 [==============================] - 0s 156us/step - loss: 0.3117 - acc: 0.8576
Epoch 93/1000
639/639

639/639 [==============================] - 0s 81us/step - loss: 0.2283 - acc: 0.9108
Epoch 165/1000
639/639 [==============================] - 0s 81us/step - loss: 0.2277 - acc: 0.9124
Epoch 166/1000
639/639 [==============================] - 0s 75us/step - loss: 0.2263 - acc: 0.9139
Epoch 167/1000
639/639 [==============================] - 0s 75us/step - loss: 0.2249 - acc: 0.9124
Epoch 168/1000
639/639 [==============================] - 0s 69us/step - loss: 0.2228 - acc: 0.9186
Epoch 169/1000
639/639 [==============================] - 0s 69us/step - loss: 0.2213 - acc: 0.9171
Epoch 170/1000
639/639 [==============================] - 0s 113us/step - loss: 0.2236 - acc: 0.9186
Epoch 171/1000
639/639 [==============================] - 0s 113us/step - loss: 0.2216 - acc: 0.9186
Epoch 172/1000
639/639 [==============================] - 0s 88us/step - loss: 0.2194 - acc: 0.9218
Epoch 173/1000
639/639 [==============================] - 0s 81us/step - loss: 0.2190 - acc: 0.9186
Epoch 174/100

639/639 [==============================] - 0s 88us/step - loss: 0.1439 - acc: 0.9468
Epoch 246/1000
639/639 [==============================] - 0s 106us/step - loss: 0.1420 - acc: 0.9484
Epoch 247/1000
639/639 [==============================] - 0s 81us/step - loss: 0.1404 - acc: 0.9515
Epoch 248/1000
639/639 [==============================] - 0s 75us/step - loss: 0.1407 - acc: 0.9499
Epoch 249/1000
639/639 [==============================] - 0s 131us/step - loss: 0.1416 - acc: 0.9515
Epoch 250/1000
639/639 [==============================] - 0s 88us/step - loss: 0.1419 - acc: 0.9515
Epoch 251/1000
639/639 [==============================] - 0s 88us/step - loss: 0.1397 - acc: 0.9468
Epoch 252/1000
639/639 [==============================] - 0s 106us/step - loss: 0.1377 - acc: 0.9484
Epoch 253/1000
639/639 [==============================] - 0s 100us/step - loss: 0.1337 - acc: 0.9562
Epoch 254/1000
639/639 [==============================] - 0s 106us/step - loss: 0.1371 - acc: 0.9499
Epoch 255/

639/639 [==============================] - 0s 69us/step - loss: 0.0985 - acc: 0.9577
Epoch 327/1000
639/639 [==============================] - 0s 138us/step - loss: 0.0980 - acc: 0.9656
Epoch 328/1000
639/639 [==============================] - 0s 106us/step - loss: 0.0963 - acc: 0.9577
Epoch 329/1000
639/639 [==============================] - 0s 88us/step - loss: 0.0955 - acc: 0.9656
Epoch 330/1000
639/639 [==============================] - 0s 100us/step - loss: 0.0941 - acc: 0.9624
Epoch 331/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0960 - acc: 0.9640
Epoch 332/1000
639/639 [==============================] - 0s 81us/step - loss: 0.0942 - acc: 0.9656
Epoch 333/1000
639/639 [==============================] - 0s 119us/step - loss: 0.0945 - acc: 0.9609
Epoch 334/1000
639/639 [==============================] - 0s 138us/step - loss: 0.0938 - acc: 0.9687
Epoch 335/1000
639/639 [==============================] - 0s 106us/step - loss: 0.0954 - acc: 0.9593
Epoch 336

639/639 [==============================] - 0s 56us/step - loss: 0.0694 - acc: 0.9750
Epoch 408/1000
639/639 [==============================] - 0s 56us/step - loss: 0.0682 - acc: 0.9750
Epoch 409/1000
639/639 [==============================] - 0s 63us/step - loss: 0.0714 - acc: 0.9703
Epoch 410/1000
639/639 [==============================] - 0s 63us/step - loss: 0.0752 - acc: 0.9750
Epoch 411/1000
639/639 [==============================] - 0s 56us/step - loss: 0.0712 - acc: 0.9687
Epoch 412/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0706 - acc: 0.9734
Epoch 413/1000
639/639 [==============================] - 0s 63us/step - loss: 0.0686 - acc: 0.9734
Epoch 414/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0690 - acc: 0.9734
Epoch 415/1000
639/639 [==============================] - 0s 63us/step - loss: 0.0683 - acc: 0.9765
Epoch 416/1000
639/639 [==============================] - 0s 50us/step - loss: 0.0664 - acc: 0.9765
Epoch 417/1000


639/639 [==============================] - ETA: 0s - loss: 0.0466 - acc: 0.984 - 0s 113us/step - loss: 0.0516 - acc: 0.9812
Epoch 489/1000
639/639 [==============================] - 0s 81us/step - loss: 0.0521 - acc: 0.9812
Epoch 490/1000
639/639 [==============================] - 0s 94us/step - loss: 0.0512 - acc: 0.9812
Epoch 491/1000
639/639 [==============================] - 0s 106us/step - loss: 0.0525 - acc: 0.9781
Epoch 492/1000
639/639 [==============================] - 0s 125us/step - loss: 0.0518 - acc: 0.9812
Epoch 493/1000
639/639 [==============================] - 0s 81us/step - loss: 0.0528 - acc: 0.9797
Epoch 494/1000
639/639 [==============================] - 0s 88us/step - loss: 0.0536 - acc: 0.9781
Epoch 495/1000
639/639 [==============================] - 0s 81us/step - loss: 0.0544 - acc: 0.9797
Epoch 496/1000
639/639 [==============================] - 0s 75us/step - loss: 0.0581 - acc: 0.9750
Epoch 497/1000
639/639 [==============================] - 0s 69us/step - l

639/639 [==============================] - 0s 75us/step - loss: 0.0488 - acc: 0.9781
Epoch 570/1000
639/639 [==============================] - 0s 75us/step - loss: 0.0445 - acc: 0.9812
Epoch 571/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0452 - acc: 0.9812
Epoch 572/1000
639/639 [==============================] - 0s 144us/step - loss: 0.0448 - acc: 0.9812
Epoch 573/1000
639/639 [==============================] - 0s 81us/step - loss: 0.0462 - acc: 0.9797
Epoch 574/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0435 - acc: 0.9812
Epoch 575/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0459 - acc: 0.9797
Epoch 576/1000
639/639 [==============================] - 0s 81us/step - loss: 0.0429 - acc: 0.9828
Epoch 577/1000
639/639 [==============================] - 0s 81us/step - loss: 0.0430 - acc: 0.9812
Epoch 578/1000
639/639 [==============================] - 0s 88us/step - loss: 0.0422 - acc: 0.9828
Epoch 579/1000

639/639 [==============================] - 0s 75us/step - loss: 0.0404 - acc: 0.9828
Epoch 651/1000
639/639 [==============================] - 0s 75us/step - loss: 0.0393 - acc: 0.9828
Epoch 652/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0393 - acc: 0.9828
Epoch 653/1000
639/639 [==============================] - 0s 49us/step - loss: 0.0398 - acc: 0.9828
Epoch 654/1000
639/639 [==============================] - 0s 74us/step - loss: 0.0404 - acc: 0.9812
Epoch 655/1000
639/639 [==============================] - 0s 75us/step - loss: 0.0392 - acc: 0.9828
Epoch 656/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0374 - acc: 0.9828
Epoch 657/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0374 - acc: 0.9828
Epoch 658/1000
639/639 [==============================] - 0s 73us/step - loss: 0.0376 - acc: 0.9828
Epoch 659/1000
639/639 [==============================] - 0s 56us/step - loss: 0.0371 - acc: 0.9828
Epoch 660/1000


Epoch 732/1000
639/639 [==============================] - 0s 75us/step - loss: 0.0347 - acc: 0.9828
Epoch 733/1000
639/639 [==============================] - 0s 75us/step - loss: 0.0348 - acc: 0.9828
Epoch 734/1000
639/639 [==============================] - 0s 81us/step - loss: 0.0345 - acc: 0.9828
Epoch 735/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0349 - acc: 0.9828
Epoch 736/1000
639/639 [==============================] - 0s 75us/step - loss: 0.0352 - acc: 0.9828
Epoch 737/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0348 - acc: 0.9828
Epoch 738/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0345 - acc: 0.9828
Epoch 739/1000
639/639 [==============================] - 0s 75us/step - loss: 0.0344 - acc: 0.9828
Epoch 740/1000
639/639 [==============================] - ETA: 0s - loss: 0.0410 - acc: 1.000 - 0s 75us/step - loss: 0.0351 - acc: 0.9828
Epoch 741/1000
639/639 [==============================] - 0s 8

639/639 [==============================] - 0s 63us/step - loss: 0.0506 - acc: 0.9734
Epoch 814/1000
639/639 [==============================] - 0s 81us/step - loss: 0.0399 - acc: 0.9828
Epoch 815/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0352 - acc: 0.9828
Epoch 816/1000
639/639 [==============================] - 0s 81us/step - loss: 0.0345 - acc: 0.9828
Epoch 817/1000
639/639 [==============================] - 0s 138us/step - loss: 0.0343 - acc: 0.9828
Epoch 818/1000
639/639 [==============================] - 0s 113us/step - loss: 0.0343 - acc: 0.9828
Epoch 819/1000
639/639 [==============================] - 0s 106us/step - loss: 0.0343 - acc: 0.9828
Epoch 820/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0339 - acc: 0.9828
Epoch 821/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0338 - acc: 0.9828
Epoch 822/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0336 - acc: 0.9828
Epoch 823/10

Epoch 895/1000
639/639 [==============================] - 0s 81us/step - loss: 0.0339 - acc: 0.9828
Epoch 896/1000
639/639 [==============================] - 0s 94us/step - loss: 0.0337 - acc: 0.9828
Epoch 897/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0336 - acc: 0.9828
Epoch 898/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0340 - acc: 0.9828
Epoch 899/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0336 - acc: 0.9828
Epoch 900/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0333 - acc: 0.9828
Epoch 901/1000
639/639 [==============================] - 0s 75us/step - loss: 0.0331 - acc: 0.9828
Epoch 902/1000
639/639 [==============================] - 0s 75us/step - loss: 0.0334 - acc: 0.9828
Epoch 903/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0332 - acc: 0.9828
Epoch 904/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0331 - acc: 0.9828


639/639 [==============================] - 0s 94us/step - loss: 0.0327 - acc: 0.9828
Epoch 977/1000
639/639 [==============================] - 0s 119us/step - loss: 0.0326 - acc: 0.9828
Epoch 978/1000
639/639 [==============================] - 0s 78us/step - loss: 0.0327 - acc: 0.9828
Epoch 979/1000
639/639 [==============================] - 0s 75us/step - loss: 0.0325 - acc: 0.9828
Epoch 980/1000
639/639 [==============================] - 0s 75us/step - loss: 0.0325 - acc: 0.9828
Epoch 981/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0325 - acc: 0.9828
Epoch 982/1000
639/639 [==============================] - 0s 69us/step - loss: 0.0325 - acc: 0.9828
Epoch 983/1000
639/639 [==============================] - 0s 75us/step - loss: 0.0325 - acc: 0.9828
Epoch 984/1000
639/639 [==============================] - 0s 75us/step - loss: 0.0326 - acc: 0.9828
Epoch 985/1000
639/639 [==============================] - 0s 63us/step - loss: 0.0327 - acc: 0.9828
Epoch 986/1000

In [166]:
y_pred=model.predict(x_test)

In [167]:
y_pred

array([[5.74886799e-05],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [7.94345140e-03],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.34587288e-04],
       [1.74326301e-01],
       [0.00000000e+00],
       [2.57790089e-05],
       [1.07467175e-04],
       [0.00000000e+00],
       [9.97371733e-01],
       [0.00000000e+00],
       [0.00000000e+00],
       [5.96046448e-08],
       [6.37624741e-01],
       [7.15255737e-07],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.84386969e-04],
       [0.00000000e+00],
       [1.84774399e-06],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.49011612e-07],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],


In [168]:
y_pred=(y_pred>0.5)

In [169]:
y_pred

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [

In [170]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [171]:
cm

array([[119,  18],
       [ 20,   3]], dtype=int64)

In [172]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7625

In [173]:
y_pred1=model.predict(sc.transform(np.array([[0,0,1,1,0,1,0,1,1,1,0,1,42,921,3,4011,0,1,3,8,2,9]])))

C:\anaco\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [174]:
y_pred1=(y_pred1>0.5)

In [175]:
y_pred1

array([[False]])